// export { default as StickyHead } from "./stickyHead/StickyHead.jsx";
export { default as Navbar } from "./navbar/Navbar.jsx";
export { default as Home } from "./home/Home.jsx";
// export { default as FutureTech } from "./futureTech/FutureTech.jsx";
// export { default as Feautres } from "./features/Features.jsx";
// export { default as Footer } from "./footer/Footer.jsx";
// export { default as Explore } from "./explore/Explore.jsx";
// export { default as Category } from "./category/Category.jsx";
// export { default as Resources } from "./resources/Resources.jsx";
// export { default as ResourceContent } from "./resourceContent/ResourceContent.jsx";
// export { default as RealReader } from "./realReader/RealReader.jsx";
// export { default as Testimonial } from "./testimonial/Testimonial.jsx";
